on:
  push:
    paths:
      - '*.md'

name: generate-vimdoc

jobs:
  generate-vimdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: command.nvim
          version: "Neovim >= 0.9.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(vimdoc):auto generate"
